---
title: "KNN-CO2"
output: html_document
---

```{r setup, include=FALSE}
start.time <- Sys.time()
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library (FNN)
library(caret)
library (class)
install.packages("e1071")

co2 <- read_csv('co2.csv')
co2$Y_Categorical =  ifelse(as.vector(co2$`Total greenhouse gas emissions per capita(t of CO2 equivalent)`) > 5.0, 1, 0)
co2$Y_Emission_Level =  ifelse(as.vector(co2$`Total greenhouse gas emissions per capita(t of CO2 equivalent)`) > 5.0,'High', 'Low')

co2<-data.frame(co2)

#'Urban population (% of total population)`  +    
#'`Population growth (annual %)` +                                                     
# `Mortality rate, under-5 (per 1,000 live births)` +                               
# `Primary completion rate, total (% of relevant age group)`  +                           
# `Population in urban agglomerations of more than 1 million (% of total population)` +
# `Energy use (kg of oil equivalent per capita)` +                                   
# `Electric power consumption (kWh per capita)`  +                                   
# `Energy use (kg of oil equivalent) per $1,000 GDP (constant 2011 PPP)` +         
# `Renewable electricity output (% of total electricity output)` ;



co2_1<-co2[,c(1,2,3,6,7,9,15,16,17,18,30,31)]
```


```{r cars}
set.seed(123) 

train.index <- sample(row.names(co2), 0.6*dim(co2)[1])  
valid.index <- setdiff(row.names(co2), train.index)  
train.df <- co2_1[train.index, ]
valid.df <- co2_1[valid.index, ]



# initialize normalized training, validation data, 
train.norm.df <- train.df
valid.norm.df <- valid.df

train_labels<-train.df[,11]
test_labels<-valid.df[,11]

norm.values <- preProcess(train.df[, 2:10], method=c("center", "scale"))
train.norm.df[, 2:10] <- predict(norm.values, train.df[, 2:10])
valid.norm.df[, 2:10] <- predict(norm.values, valid.df[, 2:10])

sqrt(206)

accuracy.df <- data.frame(k = seq(1, 14, 1), accuracy = rep(0, 14))



for(i in 1:14) {          
  knn.pred <- knn(train.norm.df[, 2:10], valid.norm.df[, 2:10], 
                  cl = train_labels, k = i)
  accuracy.df[i, 2] <- confusionMatrix(knn.pred,factor(test_labels))$overall[1] 
  
  
}

accuracy.df

knn.pred.new <- knn(train.norm.df[, 2:10], valid.norm.df[, 2:10], 
                    cl = train_labels, k = 1)  
confusionMatrix(knn.pred.new,factor(test_labels))


knn.pred.final <- knn(train.norm.df[, 2:10], valid.norm.df[, 2:10], 
                    cl = train_labels, k = 8) 

confusionMatrix(knn.pred.final,factor(test_labels))

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```


